
// const url = 'https://weatherapi-com.p.rapidapi.com/forecast.json?q=London&days=3';
// const options = {
// 	method: 'GET',
// 	headers: {
// 		'X-RapidAPI-Key': '819be45fdemsh99c70ad79a6a00ep1be7a6jsn144924b4a02d',
// 		'X-RapidAPI-Host': 'weatherapi-com.p.rapidapi.com'
// 	}
// };

// try {
// 	const response = await fetch(url, options);
// 	const result = await response.text();
// 	console.log(result);
// } catch (error) {
// 	console.error(error);
// }
// ======================================

// forcastday=[day1,day2,day3]
// hour=[1,2,3,...,4]

// ======================================

// const data = {
//   location: {
//     name: "London",
//     region: "City of London, Greater London",
//     country: "United Kingdom",
//     lat: 51.52,
//     lon: -0.11,
//     tz_id: "Europe/London",
//     localtime_epoch: 1691259518,
//     localtime: "2023-08-05 19:18",
//   },
//   current: {
//     last_updated_epoch: 1691259300,
//     last_updated: "2023-08-05 19:15",
//     temp_c: 15.0,
//     temp_f: 59.0,
//     is_day: 1,
//     condition: {
//       text: "Overcast",
//       icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//       code: 1009,
//     },
//     wind_mph: 17.4,
//     wind_kph: 28.1,
//     wind_degree: 350,
//     wind_dir: "N",
//     pressure_mb: 1005.0,
//     pressure_in: 29.68,
//     precip_mm: 0.3,
//     precip_in: 0.01,
//     humidity: 88,
//     cloud: 100,
//     feelslike_c: 13.8,
//     feelslike_f: 56.8,
//     vis_km: 10.0,
//     vis_miles: 6.0,
//     uv: 5.0,
//     gust_mph: 15.9,
//     gust_kph: 25.6,
//   },
//   forecast: {
//     forecastday: [
//       {
//         date: "2023-08-05",
//         date_epoch: 1691193600,
//         day: {
//           maxtemp_c: 17.7,
//           maxtemp_f: 63.9,
//           mintemp_c: 12.2,
//           mintemp_f: 54.0,
//           avgtemp_c: 14.2,
//           avgtemp_f: 57.6,
//           maxwind_mph: 14.5,
//           maxwind_kph: 23.4,
//           totalprecip_mm: 19.1,
//           totalprecip_in: 0.75,
//           totalsnow_cm: 0.0,
//           avgvis_km: 8.4,
//           avgvis_miles: 5.0,
//           avghumidity: 85.0,
//           daily_will_it_rain: 1,
//           daily_chance_of_rain: 99,
//           daily_will_it_snow: 0,
//           daily_chance_of_snow: 0,
//           condition: {
//             text: "Moderate rain",
//             icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
//             code: 1189,
//           },
//           uv: 3.0,
//         },
//         astro: {
//           sunrise: "05:30 AM",
//           sunset: "08:42 PM",
//           moonrise: "10:32 PM",
//           moonset: "10:19 AM",
//           moon_phase: "Waning Gibbous",
//           moon_illumination: "85",
//           is_moon_up: 1,
//           is_sun_up: 0,
//         },
//         hour: [
//           {
//             time_epoch: 1691190000,
//             time: "2023-08-05 00:00",
//             temp_c: 14.7,
//             temp_f: 58.5,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 5.6,
//             wind_kph: 9.0,
//             wind_degree: 244,
//             wind_dir: "WSW",
//             pressure_mb: 1017.0,
//             pressure_in: 30.02,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 71,
//             cloud: 55,
//             feelslike_c: 14.4,
//             feelslike_f: 57.9,
//             windchill_c: 14.4,
//             windchill_f: 57.9,
//             heatindex_c: 14.7,
//             heatindex_f: 58.5,
//             dewpoint_c: 9.5,
//             dewpoint_f: 49.1,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 8.1,
//             gust_kph: 13.0,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691193600,
//             time: "2023-08-05 01:00",
//             temp_c: 14.5,
//             temp_f: 58.1,
//             is_day: 0,
//             condition: {
//               text: "Cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
//               code: 1006,
//             },
//             wind_mph: 5.8,
//             wind_kph: 9.4,
//             wind_degree: 244,
//             wind_dir: "WSW",
//             pressure_mb: 1016.0,
//             pressure_in: 30.0,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 74,
//             cloud: 85,
//             feelslike_c: 14.1,
//             feelslike_f: 57.4,
//             windchill_c: 14.1,
//             windchill_f: 57.4,
//             heatindex_c: 14.5,
//             heatindex_f: 58.1,
//             dewpoint_c: 9.9,
//             dewpoint_f: 49.8,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 8.3,
//             gust_kph: 13.3,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691197200,
//             time: "2023-08-05 02:00",
//             temp_c: 14.1,
//             temp_f: 57.4,
//             is_day: 0,
//             condition: {
//               text: "Cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
//               code: 1006,
//             },
//             wind_mph: 6.5,
//             wind_kph: 10.4,
//             wind_degree: 225,
//             wind_dir: "SW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 77,
//             cloud: 69,
//             feelslike_c: 13.5,
//             feelslike_f: 56.3,
//             windchill_c: 13.5,
//             windchill_f: 56.3,
//             heatindex_c: 14.1,
//             heatindex_f: 57.4,
//             dewpoint_c: 10.1,
//             dewpoint_f: 50.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 9.2,
//             gust_kph: 14.8,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691200800,
//             time: "2023-08-05 03:00",
//             temp_c: 13.7,
//             temp_f: 56.7,
//             is_day: 0,
//             condition: {
//               text: "Light rain shower",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
//               code: 1240,
//             },
//             wind_mph: 6.0,
//             wind_kph: 9.7,
//             wind_degree: 223,
//             wind_dir: "SW",
//             pressure_mb: 1014.0,
//             pressure_in: 29.96,
//             precip_mm: 0.2,
//             precip_in: 0.01,
//             humidity: 80,
//             cloud: 100,
//             feelslike_c: 13.1,
//             feelslike_f: 55.6,
//             windchill_c: 13.1,
//             windchill_f: 55.6,
//             heatindex_c: 13.7,
//             heatindex_f: 56.7,
//             dewpoint_c: 10.4,
//             dewpoint_f: 50.7,
//             will_it_rain: 0,
//             chance_of_rain: 63,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 8.9,
//             gust_kph: 14.4,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691204400,
//             time: "2023-08-05 04:00",
//             temp_c: 13.3,
//             temp_f: 55.9,
//             is_day: 0,
//             condition: {
//               text: "Cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
//               code: 1006,
//             },
//             wind_mph: 7.4,
//             wind_kph: 11.9,
//             wind_degree: 226,
//             wind_dir: "SW",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 81,
//             cloud: 82,
//             feelslike_c: 12.3,
//             feelslike_f: 54.1,
//             windchill_c: 12.3,
//             windchill_f: 54.1,
//             heatindex_c: 13.3,
//             heatindex_f: 55.9,
//             dewpoint_c: 10.1,
//             dewpoint_f: 50.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 10.7,
//             gust_kph: 17.3,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691208000,
//             time: "2023-08-05 05:00",
//             temp_c: 13.0,
//             temp_f: 55.4,
//             is_day: 0,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
//               code: 1063,
//             },
//             wind_mph: 6.0,
//             wind_kph: 9.7,
//             wind_degree: 190,
//             wind_dir: "S",
//             pressure_mb: 1013.0,
//             pressure_in: 29.91,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 82,
//             cloud: 100,
//             feelslike_c: 12.3,
//             feelslike_f: 54.1,
//             windchill_c: 12.3,
//             windchill_f: 54.1,
//             heatindex_c: 13.0,
//             heatindex_f: 55.4,
//             dewpoint_c: 10.0,
//             dewpoint_f: 50.0,
//             will_it_rain: 0,
//             chance_of_rain: 63,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 8.5,
//             gust_kph: 13.7,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691211600,
//             time: "2023-08-05 06:00",
//             temp_c: 12.4,
//             temp_f: 54.3,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 5.8,
//             wind_kph: 9.4,
//             wind_degree: 167,
//             wind_dir: "SSE",
//             pressure_mb: 1012.0,
//             pressure_in: 29.88,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 88,
//             cloud: 100,
//             feelslike_c: 11.6,
//             feelslike_f: 52.9,
//             windchill_c: 11.6,
//             windchill_f: 52.9,
//             heatindex_c: 12.4,
//             heatindex_f: 54.3,
//             dewpoint_c: 10.5,
//             dewpoint_f: 50.9,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 8.1,
//             gust_kph: 13.0,
//             uv: 3.0,
//           },
//           {
//             time_epoch: 1691215200,
//             time: "2023-08-05 07:00",
//             temp_c: 12.4,
//             temp_f: 54.3,
//             is_day: 1,
//             condition: {
//               text: "Light rain",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
//               code: 1183,
//             },
//             wind_mph: 8.7,
//             wind_kph: 14.0,
//             wind_degree: 169,
//             wind_dir: "S",
//             pressure_mb: 1010.0,
//             pressure_in: 29.83,
//             precip_mm: 1.4,
//             precip_in: 0.06,
//             humidity: 93,
//             cloud: 100,
//             feelslike_c: 11.0,
//             feelslike_f: 51.8,
//             windchill_c: 11.0,
//             windchill_f: 51.8,
//             heatindex_c: 12.4,
//             heatindex_f: 54.3,
//             dewpoint_c: 11.3,
//             dewpoint_f: 52.3,
//             will_it_rain: 0,
//             chance_of_rain: 62,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 9.0,
//             vis_miles: 5.0,
//             gust_mph: 12.3,
//             gust_kph: 19.8,
//             uv: 3.0,
//           },
//           {
//             time_epoch: 1691218800,
//             time: "2023-08-05 08:00",
//             temp_c: 12.9,
//             temp_f: 55.2,
//             is_day: 1,
//             condition: {
//               text: "Light rain",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
//               code: 1183,
//             },
//             wind_mph: 9.4,
//             wind_kph: 15.1,
//             wind_degree: 171,
//             wind_dir: "S",
//             pressure_mb: 1008.0,
//             pressure_in: 29.77,
//             precip_mm: 1.7,
//             precip_in: 0.07,
//             humidity: 94,
//             cloud: 100,
//             feelslike_c: 11.5,
//             feelslike_f: 52.7,
//             windchill_c: 11.5,
//             windchill_f: 52.7,
//             heatindex_c: 12.9,
//             heatindex_f: 55.2,
//             dewpoint_c: 11.9,
//             dewpoint_f: 53.4,
//             will_it_rain: 0,
//             chance_of_rain: 62,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 9.0,
//             vis_miles: 5.0,
//             gust_mph: 13.9,
//             gust_kph: 22.3,
//             uv: 3.0,
//           },
//           {
//             time_epoch: 1691222400,
//             time: "2023-08-05 09:00",
//             temp_c: 13.7,
//             temp_f: 56.7,
//             is_day: 1,
//             condition: {
//               text: "Heavy rain",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
//               code: 1195,
//             },
//             wind_mph: 16.3,
//             wind_kph: 26.3,
//             wind_degree: 194,
//             wind_dir: "SSW",
//             pressure_mb: 1007.0,
//             pressure_in: 29.73,
//             precip_mm: 9.0,
//             precip_in: 0.35,
//             humidity: 94,
//             cloud: 100,
//             feelslike_c: 11.6,
//             feelslike_f: 52.9,
//             windchill_c: 11.6,
//             windchill_f: 52.9,
//             heatindex_c: 13.7,
//             heatindex_f: 56.7,
//             dewpoint_c: 12.7,
//             dewpoint_f: 54.9,
//             will_it_rain: 0,
//             chance_of_rain: 61,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 5.0,
//             vis_miles: 3.0,
//             gust_mph: 24.4,
//             gust_kph: 39.2,
//             uv: 3.0,
//           },
//           {
//             time_epoch: 1691226000,
//             time: "2023-08-05 10:00",
//             temp_c: 14.4,
//             temp_f: 57.9,
//             is_day: 1,
//             condition: {
//               text: "Light rain",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
//               code: 1183,
//             },
//             wind_mph: 13.9,
//             wind_kph: 22.3,
//             wind_degree: 197,
//             wind_dir: "SSW",
//             pressure_mb: 1006.0,
//             pressure_in: 29.7,
//             precip_mm: 2.3,
//             precip_in: 0.09,
//             humidity: 95,
//             cloud: 100,
//             feelslike_c: 12.8,
//             feelslike_f: 55.0,
//             windchill_c: 12.8,
//             windchill_f: 55.0,
//             heatindex_c: 14.4,
//             heatindex_f: 57.9,
//             dewpoint_c: 13.7,
//             dewpoint_f: 56.7,
//             will_it_rain: 0,
//             chance_of_rain: 61,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 9.0,
//             vis_miles: 5.0,
//             gust_mph: 20.4,
//             gust_kph: 32.8,
//             uv: 3.0,
//           },
//           {
//             time_epoch: 1691229600,
//             time: "2023-08-05 11:00",
//             temp_c: 15.8,
//             temp_f: 60.4,
//             is_day: 1,
//             condition: {
//               text: "Light rain shower",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
//               code: 1240,
//             },
//             wind_mph: 11.2,
//             wind_kph: 18.0,
//             wind_degree: 234,
//             wind_dir: "SW",
//             pressure_mb: 1005.0,
//             pressure_in: 29.67,
//             precip_mm: 2.0,
//             precip_in: 0.08,
//             humidity: 91,
//             cloud: 96,
//             feelslike_c: 15.8,
//             feelslike_f: 60.4,
//             windchill_c: 15.8,
//             windchill_f: 60.4,
//             heatindex_c: 15.8,
//             heatindex_f: 60.4,
//             dewpoint_c: 14.3,
//             dewpoint_f: 57.7,
//             will_it_rain: 0,
//             chance_of_rain: 61,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 17.2,
//             gust_kph: 27.7,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691233200,
//             time: "2023-08-05 12:00",
//             temp_c: 18.5,
//             temp_f: 65.3,
//             is_day: 1,
//             condition: {
//               text: "Heavy rain",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
//               code: 1195,
//             },
//             wind_mph: 13.9,
//             wind_kph: 22.3,
//             wind_degree: 283,
//             wind_dir: "WNW",
//             pressure_mb: 1004.0,
//             pressure_in: 29.66,
//             precip_mm: 10.4,
//             precip_in: 0.41,
//             humidity: 81,
//             cloud: 100,
//             feelslike_c: 18.5,
//             feelslike_f: 65.3,
//             windchill_c: 18.5,
//             windchill_f: 65.3,
//             heatindex_c: 18.5,
//             heatindex_f: 65.3,
//             dewpoint_c: 15.1,
//             dewpoint_f: 59.2,
//             will_it_rain: 0,
//             chance_of_rain: 60,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 5.0,
//             vis_miles: 3.0,
//             gust_mph: 19.5,
//             gust_kph: 31.3,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691236800,
//             time: "2023-08-05 13:00",
//             temp_c: 15.8,
//             temp_f: 60.4,
//             is_day: 1,
//             condition: {
//               text: "Light rain shower",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
//               code: 1240,
//             },
//             wind_mph: 17.9,
//             wind_kph: 28.8,
//             wind_degree: 327,
//             wind_dir: "NNW",
//             pressure_mb: 1007.0,
//             pressure_in: 29.73,
//             precip_mm: 0.3,
//             precip_in: 0.01,
//             humidity: 82,
//             cloud: 73,
//             feelslike_c: 15.8,
//             feelslike_f: 60.4,
//             windchill_c: 15.8,
//             windchill_f: 60.4,
//             heatindex_c: 15.8,
//             heatindex_f: 60.4,
//             dewpoint_c: 12.8,
//             dewpoint_f: 55.0,
//             will_it_rain: 0,
//             chance_of_rain: 63,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 21.3,
//             gust_kph: 34.2,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691240400,
//             time: "2023-08-05 14:00",
//             temp_c: 16.1,
//             temp_f: 61.0,
//             is_day: 1,
//             condition: {
//               text: "Light rain shower",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
//               code: 1240,
//             },
//             wind_mph: 15.7,
//             wind_kph: 25.2,
//             wind_degree: 326,
//             wind_dir: "NNW",
//             pressure_mb: 1008.0,
//             pressure_in: 29.77,
//             precip_mm: 0.2,
//             precip_in: 0.01,
//             humidity: 71,
//             cloud: 87,
//             feelslike_c: 16.1,
//             feelslike_f: 61.0,
//             windchill_c: 16.1,
//             windchill_f: 61.0,
//             heatindex_c: 16.1,
//             heatindex_f: 61.0,
//             dewpoint_c: 10.8,
//             dewpoint_f: 51.4,
//             will_it_rain: 0,
//             chance_of_rain: 60,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 18.6,
//             gust_kph: 29.9,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691244000,
//             time: "2023-08-05 15:00",
//             temp_c: 17.3,
//             temp_f: 63.1,
//             is_day: 1,
//             condition: {
//               text: "Light rain shower",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
//               code: 1240,
//             },
//             wind_mph: 15.2,
//             wind_kph: 24.5,
//             wind_degree: 319,
//             wind_dir: "NW",
//             pressure_mb: 1009.0,
//             pressure_in: 29.79,
//             precip_mm: 0.4,
//             precip_in: 0.02,
//             humidity: 63,
//             cloud: 67,
//             feelslike_c: 17.3,
//             feelslike_f: 63.1,
//             windchill_c: 17.3,
//             windchill_f: 63.1,
//             heatindex_c: 17.3,
//             heatindex_f: 63.1,
//             dewpoint_c: 10.1,
//             dewpoint_f: 50.2,
//             will_it_rain: 0,
//             chance_of_rain: 59,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 18.3,
//             gust_kph: 29.5,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691247600,
//             time: "2023-08-05 16:00",
//             temp_c: 17.8,
//             temp_f: 64.0,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 14.1,
//             wind_kph: 22.7,
//             wind_degree: 311,
//             wind_dir: "NW",
//             pressure_mb: 1010.0,
//             pressure_in: 29.82,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 61,
//             cloud: 60,
//             feelslike_c: 17.8,
//             feelslike_f: 64.0,
//             windchill_c: 17.8,
//             windchill_f: 64.0,
//             heatindex_c: 17.8,
//             heatindex_f: 64.0,
//             dewpoint_c: 10.1,
//             dewpoint_f: 50.2,
//             will_it_rain: 1,
//             chance_of_rain: 76,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 17.0,
//             gust_kph: 27.4,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691251200,
//             time: "2023-08-05 17:00",
//             temp_c: 17.9,
//             temp_f: 64.2,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 13.4,
//             wind_kph: 21.6,
//             wind_degree: 299,
//             wind_dir: "WNW",
//             pressure_mb: 1011.0,
//             pressure_in: 29.84,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 61,
//             cloud: 64,
//             feelslike_c: 17.9,
//             feelslike_f: 64.2,
//             windchill_c: 17.9,
//             windchill_f: 64.2,
//             heatindex_c: 17.9,
//             heatindex_f: 64.2,
//             dewpoint_c: 10.4,
//             dewpoint_f: 50.7,
//             will_it_rain: 1,
//             chance_of_rain: 81,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 16.1,
//             gust_kph: 25.9,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691254800,
//             time: "2023-08-05 18:00",
//             temp_c: 16.7,
//             temp_f: 62.1,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 12.1,
//             wind_kph: 19.4,
//             wind_degree: 305,
//             wind_dir: "NW",
//             pressure_mb: 1011.0,
//             pressure_in: 29.86,
//             precip_mm: 0.4,
//             precip_in: 0.02,
//             humidity: 63,
//             cloud: 75,
//             feelslike_c: 16.7,
//             feelslike_f: 62.1,
//             windchill_c: 16.7,
//             windchill_f: 62.1,
//             heatindex_c: 16.7,
//             heatindex_f: 62.1,
//             dewpoint_c: 9.5,
//             dewpoint_f: 49.1,
//             will_it_rain: 0,
//             chance_of_rain: 67,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 9.0,
//             vis_miles: 5.0,
//             gust_mph: 15.9,
//             gust_kph: 25.6,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691258400,
//             time: "2023-08-05 19:00",
//             temp_c: 15.9,
//             temp_f: 60.6,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 11.6,
//             wind_kph: 18.7,
//             wind_degree: 297,
//             wind_dir: "WNW",
//             pressure_mb: 1012.0,
//             pressure_in: 29.88,
//             precip_mm: 0.3,
//             precip_in: 0.01,
//             humidity: 66,
//             cloud: 61,
//             feelslike_c: 15.5,
//             feelslike_f: 59.9,
//             windchill_c: 15.5,
//             windchill_f: 59.9,
//             heatindex_c: 15.9,
//             heatindex_f: 60.6,
//             dewpoint_c: 9.6,
//             dewpoint_f: 49.3,
//             will_it_rain: 0,
//             chance_of_rain: 45,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 9.3,
//             vis_miles: 5.0,
//             gust_mph: 15.9,
//             gust_kph: 25.6,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691262000,
//             time: "2023-08-05 20:00",
//             temp_c: 15.2,
//             temp_f: 59.4,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 11.0,
//             wind_kph: 17.6,
//             wind_degree: 288,
//             wind_dir: "WNW",
//             pressure_mb: 1013.0,
//             pressure_in: 29.9,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 70,
//             cloud: 48,
//             feelslike_c: 14.4,
//             feelslike_f: 57.9,
//             windchill_c: 14.4,
//             windchill_f: 57.9,
//             heatindex_c: 15.2,
//             heatindex_f: 59.4,
//             dewpoint_c: 9.7,
//             dewpoint_f: 49.5,
//             will_it_rain: 0,
//             chance_of_rain: 22,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 9.7,
//             vis_miles: 6.0,
//             gust_mph: 15.9,
//             gust_kph: 25.6,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691265600,
//             time: "2023-08-05 21:00",
//             temp_c: 14.4,
//             temp_f: 57.9,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 10.5,
//             wind_kph: 16.9,
//             wind_degree: 280,
//             wind_dir: "W",
//             pressure_mb: 1013.0,
//             pressure_in: 29.92,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 74,
//             cloud: 34,
//             feelslike_c: 13.2,
//             feelslike_f: 55.8,
//             windchill_c: 13.2,
//             windchill_f: 55.8,
//             heatindex_c: 14.4,
//             heatindex_f: 57.9,
//             dewpoint_c: 9.8,
//             dewpoint_f: 49.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 15.9,
//             gust_kph: 25.6,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691269200,
//             time: "2023-08-05 22:00",
//             temp_c: 14.0,
//             temp_f: 57.2,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 10.1,
//             wind_kph: 16.2,
//             wind_degree: 277,
//             wind_dir: "W",
//             pressure_mb: 1013.0,
//             pressure_in: 29.92,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 76,
//             cloud: 29,
//             feelslike_c: 12.7,
//             feelslike_f: 54.9,
//             windchill_c: 12.7,
//             windchill_f: 54.9,
//             heatindex_c: 14.0,
//             heatindex_f: 57.2,
//             dewpoint_c: 9.8,
//             dewpoint_f: 49.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 15.4,
//             gust_kph: 24.8,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691272800,
//             time: "2023-08-05 23:00",
//             temp_c: 13.5,
//             temp_f: 56.3,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 9.8,
//             wind_kph: 15.8,
//             wind_degree: 275,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.93,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 79,
//             cloud: 24,
//             feelslike_c: 12.2,
//             feelslike_f: 54.0,
//             windchill_c: 12.2,
//             windchill_f: 54.0,
//             heatindex_c: 13.5,
//             heatindex_f: 56.3,
//             dewpoint_c: 9.9,
//             dewpoint_f: 49.8,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.8,
//             gust_kph: 23.8,
//             uv: 1.0,
//           },
//         ],
//       },
//       {
//         date: "2023-08-06",
//         date_epoch: 1691280000,
//         day: {
//           maxtemp_c: 18.5,
//           maxtemp_f: 65.3,
//           mintemp_c: 11.1,
//           mintemp_f: 52.0,
//           avgtemp_c: 14.9,
//           avgtemp_f: 58.7,
//           maxwind_mph: 12.5,
//           maxwind_kph: 20.2,
//           totalprecip_mm: 3.8,
//           totalprecip_in: 0.15,
//           totalsnow_cm: 0.0,
//           avgvis_km: 9.6,
//           avgvis_miles: 5.0,
//           avghumidity: 69.0,
//           daily_will_it_rain: 1,
//           daily_chance_of_rain: 88,
//           daily_will_it_snow: 0,
//           daily_chance_of_snow: 0,
//           condition: {
//             text: "Patchy rain possible",
//             icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//             code: 1063,
//           },
//           uv: 3.0,
//         },
//         astro: {
//           sunrise: "05:32 AM",
//           sunset: "08:40 PM",
//           moonrise: "10:45 PM",
//           moonset: "11:44 AM",
//           moon_phase: "Waning Gibbous",
//           moon_illumination: "76",
//           is_moon_up: 1,
//           is_sun_up: 0,
//         },
//         hour: [
//           {
//             time_epoch: 1691276400,
//             time: "2023-08-06 00:00",
//             temp_c: 13.1,
//             temp_f: 55.6,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 9.4,
//             wind_kph: 15.1,
//             wind_degree: 273,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 81,
//             cloud: 18,
//             feelslike_c: 11.7,
//             feelslike_f: 53.1,
//             windchill_c: 11.7,
//             windchill_f: 53.1,
//             heatindex_c: 13.1,
//             heatindex_f: 55.6,
//             dewpoint_c: 9.9,
//             dewpoint_f: 49.8,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.3,
//             gust_kph: 23.0,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691280000,
//             time: "2023-08-06 01:00",
//             temp_c: 12.8,
//             temp_f: 55.0,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 8.7,
//             wind_kph: 14.0,
//             wind_degree: 270,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 83,
//             cloud: 18,
//             feelslike_c: 11.5,
//             feelslike_f: 52.7,
//             windchill_c: 11.5,
//             windchill_f: 52.7,
//             heatindex_c: 12.8,
//             heatindex_f: 55.0,
//             dewpoint_c: 10.0,
//             dewpoint_f: 50.0,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.2,
//             gust_kph: 21.2,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691283600,
//             time: "2023-08-06 02:00",
//             temp_c: 12.6,
//             temp_f: 54.7,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 8.1,
//             wind_kph: 13.0,
//             wind_degree: 268,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 85,
//             cloud: 17,
//             feelslike_c: 11.3,
//             feelslike_f: 52.3,
//             windchill_c: 11.3,
//             windchill_f: 52.3,
//             heatindex_c: 12.6,
//             heatindex_f: 54.7,
//             dewpoint_c: 10.0,
//             dewpoint_f: 50.0,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.3,
//             gust_kph: 19.8,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691287200,
//             time: "2023-08-06 03:00",
//             temp_c: 12.3,
//             temp_f: 54.1,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 7.4,
//             wind_kph: 11.9,
//             wind_degree: 266,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 87,
//             cloud: 16,
//             feelslike_c: 11.1,
//             feelslike_f: 52.0,
//             windchill_c: 11.1,
//             windchill_f: 52.0,
//             heatindex_c: 12.3,
//             heatindex_f: 54.1,
//             dewpoint_c: 10.1,
//             dewpoint_f: 50.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.2,
//             gust_kph: 18.0,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691290800,
//             time: "2023-08-06 04:00",
//             temp_c: 12.4,
//             temp_f: 54.3,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 7.4,
//             wind_kph: 11.9,
//             wind_degree: 267,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.95,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 86,
//             cloud: 18,
//             feelslike_c: 11.2,
//             feelslike_f: 52.2,
//             windchill_c: 11.2,
//             windchill_f: 52.2,
//             heatindex_c: 12.4,
//             heatindex_f: 54.3,
//             dewpoint_c: 10.0,
//             dewpoint_f: 50.0,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.0,
//             gust_kph: 17.6,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691294400,
//             time: "2023-08-06 05:00",
//             temp_c: 12.4,
//             temp_f: 54.3,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 7.6,
//             wind_kph: 12.2,
//             wind_degree: 269,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 85,
//             cloud: 19,
//             feelslike_c: 11.2,
//             feelslike_f: 52.2,
//             windchill_c: 11.2,
//             windchill_f: 52.2,
//             heatindex_c: 12.4,
//             heatindex_f: 54.3,
//             dewpoint_c: 10.0,
//             dewpoint_f: 50.0,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 10.5,
//             gust_kph: 16.9,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691298000,
//             time: "2023-08-06 06:00",
//             temp_c: 12.5,
//             temp_f: 54.5,
//             is_day: 1,
//             condition: {
//               text: "Sunny",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
//               code: 1000,
//             },
//             wind_mph: 7.6,
//             wind_kph: 12.2,
//             wind_degree: 270,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 84,
//             cloud: 21,
//             feelslike_c: 11.3,
//             feelslike_f: 52.3,
//             windchill_c: 11.3,
//             windchill_f: 52.3,
//             heatindex_c: 12.5,
//             heatindex_f: 54.5,
//             dewpoint_c: 9.9,
//             dewpoint_f: 49.8,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 10.3,
//             gust_kph: 16.6,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691301600,
//             time: "2023-08-06 07:00",
//             temp_c: 13.8,
//             temp_f: 56.8,
//             is_day: 1,
//             condition: {
//               text: "Cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
//               code: 1006,
//             },
//             wind_mph: 8.3,
//             wind_kph: 13.3,
//             wind_degree: 276,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 77,
//             cloud: 42,
//             feelslike_c: 13.0,
//             feelslike_f: 55.4,
//             windchill_c: 13.0,
//             windchill_f: 55.4,
//             heatindex_c: 13.8,
//             heatindex_f: 56.8,
//             dewpoint_c: 9.7,
//             dewpoint_f: 49.5,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 10.5,
//             gust_kph: 16.9,
//             uv: 3.0,
//           },
//           {
//             time_epoch: 1691305200,
//             time: "2023-08-06 08:00",
//             temp_c: 15.0,
//             temp_f: 59.0,
//             is_day: 1,
//             condition: {
//               text: "Sunny",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
//               code: 1000,
//             },
//             wind_mph: 8.9,
//             wind_kph: 14.4,
//             wind_degree: 282,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 70,
//             cloud: 64,
//             feelslike_c: 14.6,
//             feelslike_f: 58.3,
//             windchill_c: 14.6,
//             windchill_f: 58.3,
//             heatindex_c: 15.0,
//             heatindex_f: 59.0,
//             dewpoint_c: 9.4,
//             dewpoint_f: 48.9,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.0,
//             gust_kph: 17.6,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691308800,
//             time: "2023-08-06 09:00",
//             temp_c: 16.3,
//             temp_f: 61.3,
//             is_day: 1,
//             condition: {
//               text: "Cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
//               code: 1006,
//             },
//             wind_mph: 9.6,
//             wind_kph: 15.5,
//             wind_degree: 288,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 63,
//             cloud: 85,
//             feelslike_c: 16.3,
//             feelslike_f: 61.3,
//             windchill_c: 16.3,
//             windchill_f: 61.3,
//             heatindex_c: 16.3,
//             heatindex_f: 61.3,
//             dewpoint_c: 9.2,
//             dewpoint_f: 48.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.2,
//             gust_kph: 18.0,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691312400,
//             time: "2023-08-06 10:00",
//             temp_c: 16.8,
//             temp_f: 62.2,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 9.6,
//             wind_kph: 15.5,
//             wind_degree: 284,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 59,
//             cloud: 90,
//             feelslike_c: 16.8,
//             feelslike_f: 62.2,
//             windchill_c: 16.8,
//             windchill_f: 62.2,
//             heatindex_c: 16.8,
//             heatindex_f: 62.2,
//             dewpoint_c: 8.7,
//             dewpoint_f: 47.7,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.4,
//             gust_kph: 18.4,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691316000,
//             time: "2023-08-06 11:00",
//             temp_c: 17.3,
//             temp_f: 63.1,
//             is_day: 1,
//             condition: {
//               text: "Cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
//               code: 1006,
//             },
//             wind_mph: 9.8,
//             wind_kph: 15.8,
//             wind_degree: 279,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 55,
//             cloud: 95,
//             feelslike_c: 17.3,
//             feelslike_f: 63.1,
//             windchill_c: 17.3,
//             windchill_f: 63.1,
//             heatindex_c: 17.3,
//             heatindex_f: 63.1,
//             dewpoint_c: 8.1,
//             dewpoint_f: 46.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.6,
//             gust_kph: 18.7,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691319600,
//             time: "2023-08-06 12:00",
//             temp_c: 17.8,
//             temp_f: 64.0,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 9.8,
//             wind_kph: 15.8,
//             wind_degree: 275,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 51,
//             cloud: 100,
//             feelslike_c: 17.8,
//             feelslike_f: 64.0,
//             windchill_c: 17.8,
//             windchill_f: 64.0,
//             heatindex_c: 17.8,
//             heatindex_f: 64.0,
//             dewpoint_c: 7.6,
//             dewpoint_f: 45.7,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.9,
//             gust_kph: 19.1,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691323200,
//             time: "2023-08-06 13:00",
//             temp_c: 18.2,
//             temp_f: 64.8,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 10.1,
//             wind_kph: 16.2,
//             wind_degree: 276,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 50,
//             cloud: 93,
//             feelslike_c: 18.2,
//             feelslike_f: 64.8,
//             windchill_c: 18.2,
//             windchill_f: 64.8,
//             heatindex_c: 18.2,
//             heatindex_f: 64.8,
//             dewpoint_c: 7.8,
//             dewpoint_f: 46.0,
//             will_it_rain: 0,
//             chance_of_rain: 28,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.1,
//             gust_kph: 19.4,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691326800,
//             time: "2023-08-06 14:00",
//             temp_c: 18.7,
//             temp_f: 65.7,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 10.5,
//             wind_kph: 16.9,
//             wind_degree: 276,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 50,
//             cloud: 85,
//             feelslike_c: 18.7,
//             feelslike_f: 65.7,
//             windchill_c: 18.7,
//             windchill_f: 65.7,
//             heatindex_c: 18.7,
//             heatindex_f: 65.7,
//             dewpoint_c: 7.9,
//             dewpoint_f: 46.2,
//             will_it_rain: 0,
//             chance_of_rain: 57,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.1,
//             gust_kph: 19.4,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691330400,
//             time: "2023-08-06 15:00",
//             temp_c: 19.1,
//             temp_f: 66.4,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 10.7,
//             wind_kph: 17.3,
//             wind_degree: 276,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 49,
//             cloud: 78,
//             feelslike_c: 19.1,
//             feelslike_f: 66.4,
//             windchill_c: 19.1,
//             windchill_f: 66.4,
//             heatindex_c: 19.1,
//             heatindex_f: 66.4,
//             dewpoint_c: 8.1,
//             dewpoint_f: 46.6,
//             will_it_rain: 1,
//             chance_of_rain: 85,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.3,
//             gust_kph: 19.8,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691334000,
//             time: "2023-08-06 16:00",
//             temp_c: 18.6,
//             temp_f: 65.5,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 10.5,
//             wind_kph: 16.9,
//             wind_degree: 271,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.1,
//             precip_in: 0.0,
//             humidity: 52,
//             cloud: 62,
//             feelslike_c: 18.6,
//             feelslike_f: 65.5,
//             windchill_c: 18.6,
//             windchill_f: 65.5,
//             heatindex_c: 18.6,
//             heatindex_f: 65.5,
//             dewpoint_c: 8.5,
//             dewpoint_f: 47.3,
//             will_it_rain: 0,
//             chance_of_rain: 57,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.5,
//             gust_kph: 20.2,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691337600,
//             time: "2023-08-06 17:00",
//             temp_c: 18.2,
//             temp_f: 64.8,
//             is_day: 1,
//             condition: {
//               text: "Patchy rain possible",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//               code: 1063,
//             },
//             wind_mph: 10.3,
//             wind_kph: 16.6,
//             wind_degree: 266,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 55,
//             cloud: 45,
//             feelslike_c: 18.2,
//             feelslike_f: 64.8,
//             windchill_c: 18.2,
//             windchill_f: 64.8,
//             heatindex_c: 18.2,
//             heatindex_f: 64.8,
//             dewpoint_c: 8.8,
//             dewpoint_f: 47.8,
//             will_it_rain: 0,
//             chance_of_rain: 28,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.5,
//             gust_kph: 20.2,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691341200,
//             time: "2023-08-06 18:00",
//             temp_c: 17.7,
//             temp_f: 63.9,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 10.1,
//             wind_kph: 16.2,
//             wind_degree: 261,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 58,
//             cloud: 28,
//             feelslike_c: 17.7,
//             feelslike_f: 63.9,
//             windchill_c: 17.7,
//             windchill_f: 63.9,
//             heatindex_c: 17.7,
//             heatindex_f: 63.9,
//             dewpoint_c: 9.2,
//             dewpoint_f: 48.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.8,
//             gust_kph: 20.5,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691344800,
//             time: "2023-08-06 19:00",
//             temp_c: 16.7,
//             temp_f: 62.1,
//             is_day: 1,
//             condition: {
//               text: "Sunny",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
//               code: 1000,
//             },
//             wind_mph: 10.1,
//             wind_kph: 16.2,
//             wind_degree: 262,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 63,
//             cloud: 26,
//             feelslike_c: 16.3,
//             feelslike_f: 61.3,
//             windchill_c: 16.3,
//             windchill_f: 61.3,
//             heatindex_c: 16.7,
//             heatindex_f: 62.1,
//             dewpoint_c: 9.5,
//             dewpoint_f: 49.1,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.4,
//             gust_kph: 21.6,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691348400,
//             time: "2023-08-06 20:00",
//             temp_c: 15.6,
//             temp_f: 60.1,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 10.3,
//             wind_kph: 16.6,
//             wind_degree: 264,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 69,
//             cloud: 23,
//             feelslike_c: 14.8,
//             feelslike_f: 58.6,
//             windchill_c: 14.8,
//             windchill_f: 58.6,
//             heatindex_c: 15.6,
//             heatindex_f: 60.1,
//             dewpoint_c: 9.8,
//             dewpoint_f: 49.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.1,
//             gust_kph: 22.7,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691352000,
//             time: "2023-08-06 21:00",
//             temp_c: 14.6,
//             temp_f: 58.3,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 10.3,
//             wind_kph: 16.6,
//             wind_degree: 265,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 74,
//             cloud: 20,
//             feelslike_c: 13.4,
//             feelslike_f: 56.1,
//             windchill_c: 13.4,
//             windchill_f: 56.1,
//             heatindex_c: 14.6,
//             heatindex_f: 58.3,
//             dewpoint_c: 10.1,
//             dewpoint_f: 50.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.8,
//             gust_kph: 23.8,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691355600,
//             time: "2023-08-06 22:00",
//             temp_c: 14.0,
//             temp_f: 57.2,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 9.8,
//             wind_kph: 15.8,
//             wind_degree: 262,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 76,
//             cloud: 20,
//             feelslike_c: 12.8,
//             feelslike_f: 55.0,
//             windchill_c: 12.8,
//             windchill_f: 55.0,
//             heatindex_c: 14.0,
//             heatindex_f: 57.2,
//             dewpoint_c: 9.9,
//             dewpoint_f: 49.8,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.1,
//             gust_kph: 22.7,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691359200,
//             time: "2023-08-06 23:00",
//             temp_c: 13.5,
//             temp_f: 56.3,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 9.4,
//             wind_kph: 15.1,
//             wind_degree: 258,
//             wind_dir: "WSW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 78,
//             cloud: 21,
//             feelslike_c: 12.2,
//             feelslike_f: 54.0,
//             windchill_c: 12.2,
//             windchill_f: 54.0,
//             heatindex_c: 13.5,
//             heatindex_f: 56.3,
//             dewpoint_c: 9.6,
//             dewpoint_f: 49.3,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.6,
//             gust_kph: 22.0,
//             uv: 1.0,
//           },
//         ],
//       },
//       {
//         date: "2023-08-07",
//         date_epoch: 1691366400,
//         day: {
//           maxtemp_c: 20.8,
//           maxtemp_f: 69.4,
//           mintemp_c: 11.4,
//           mintemp_f: 52.5,
//           avgtemp_c: 16.2,
//           avgtemp_f: 61.2,
//           maxwind_mph: 10.1,
//           maxwind_kph: 16.2,
//           totalprecip_mm: 0.4,
//           totalprecip_in: 0.02,
//           totalsnow_cm: 0.0,
//           avgvis_km: 10.0,
//           avgvis_miles: 6.0,
//           avghumidity: 64.0,
//           daily_will_it_rain: 1,
//           daily_chance_of_rain: 73,
//           daily_will_it_snow: 0,
//           daily_chance_of_snow: 0,
//           condition: {
//             text: "Patchy rain possible",
//             icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
//             code: 1063,
//           },
//           uv: 4.0,
//         },
//         astro: {
//           sunrise: "05:33 AM",
//           sunset: "08:39 PM",
//           moonrise: "11:00 PM",
//           moonset: "01:08 PM",
//           moon_phase: "Waning Gibbous",
//           moon_illumination: "65",
//           is_moon_up: 1,
//           is_sun_up: 0,
//         },
//         hour: [
//           {
//             time_epoch: 1691362800,
//             time: "2023-08-07 00:00",
//             temp_c: 12.9,
//             temp_f: 55.2,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 8.9,
//             wind_kph: 14.4,
//             wind_degree: 254,
//             wind_dir: "WSW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 79,
//             cloud: 21,
//             feelslike_c: 11.6,
//             feelslike_f: 52.9,
//             windchill_c: 11.6,
//             windchill_f: 52.9,
//             heatindex_c: 12.9,
//             heatindex_f: 55.2,
//             dewpoint_c: 9.4,
//             dewpoint_f: 48.9,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.0,
//             gust_kph: 20.9,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691366400,
//             time: "2023-08-07 01:00",
//             temp_c: 12.6,
//             temp_f: 54.7,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 8.9,
//             wind_kph: 14.4,
//             wind_degree: 254,
//             wind_dir: "WSW",
//             pressure_mb: 1014.0,
//             pressure_in: 29.95,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 80,
//             cloud: 26,
//             feelslike_c: 11.2,
//             feelslike_f: 52.2,
//             windchill_c: 11.2,
//             windchill_f: 52.2,
//             heatindex_c: 12.6,
//             heatindex_f: 54.7,
//             dewpoint_c: 9.3,
//             dewpoint_f: 48.7,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.2,
//             gust_kph: 21.2,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691370000,
//             time: "2023-08-07 02:00",
//             temp_c: 12.2,
//             temp_f: 54.0,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 9.2,
//             wind_kph: 14.8,
//             wind_degree: 253,
//             wind_dir: "WSW",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 81,
//             cloud: 31,
//             feelslike_c: 10.7,
//             feelslike_f: 51.3,
//             windchill_c: 10.7,
//             windchill_f: 51.3,
//             heatindex_c: 12.2,
//             heatindex_f: 54.0,
//             dewpoint_c: 9.1,
//             dewpoint_f: 48.4,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.2,
//             gust_kph: 21.2,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691373600,
//             time: "2023-08-07 03:00",
//             temp_c: 11.9,
//             temp_f: 53.4,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 9.2,
//             wind_kph: 14.8,
//             wind_degree: 253,
//             wind_dir: "WSW",
//             pressure_mb: 1014.0,
//             pressure_in: 29.93,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 82,
//             cloud: 36,
//             feelslike_c: 10.3,
//             feelslike_f: 50.5,
//             windchill_c: 10.3,
//             windchill_f: 50.5,
//             heatindex_c: 11.9,
//             heatindex_f: 53.4,
//             dewpoint_c: 9.0,
//             dewpoint_f: 48.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.4,
//             gust_kph: 21.6,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691377200,
//             time: "2023-08-07 04:00",
//             temp_c: 11.9,
//             temp_f: 53.4,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 9.6,
//             wind_kph: 15.5,
//             wind_degree: 260,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 81,
//             cloud: 31,
//             feelslike_c: 10.2,
//             feelslike_f: 50.4,
//             windchill_c: 10.2,
//             windchill_f: 50.4,
//             heatindex_c: 11.9,
//             heatindex_f: 53.4,
//             dewpoint_c: 8.8,
//             dewpoint_f: 47.8,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.6,
//             gust_kph: 22.0,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691380800,
//             time: "2023-08-07 05:00",
//             temp_c: 11.9,
//             temp_f: 53.4,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 10.1,
//             wind_kph: 16.2,
//             wind_degree: 266,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.94,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 80,
//             cloud: 27,
//             feelslike_c: 10.2,
//             feelslike_f: 50.4,
//             windchill_c: 10.2,
//             windchill_f: 50.4,
//             heatindex_c: 11.9,
//             heatindex_f: 53.4,
//             dewpoint_c: 8.6,
//             dewpoint_f: 47.5,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.9,
//             gust_kph: 22.3,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691384400,
//             time: "2023-08-07 06:00",
//             temp_c: 11.9,
//             temp_f: 53.4,
//             is_day: 1,
//             condition: {
//               text: "Sunny",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
//               code: 1000,
//             },
//             wind_mph: 10.5,
//             wind_kph: 16.9,
//             wind_degree: 272,
//             wind_dir: "W",
//             pressure_mb: 1014.0,
//             pressure_in: 29.95,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 79,
//             cloud: 23,
//             feelslike_c: 10.1,
//             feelslike_f: 50.2,
//             windchill_c: 10.1,
//             windchill_f: 50.2,
//             heatindex_c: 11.9,
//             heatindex_f: 53.4,
//             dewpoint_c: 8.4,
//             dewpoint_f: 47.1,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.1,
//             gust_kph: 22.7,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691388000,
//             time: "2023-08-07 07:00",
//             temp_c: 13.1,
//             temp_f: 55.6,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 11.0,
//             wind_kph: 17.6,
//             wind_degree: 278,
//             wind_dir: "W",
//             pressure_mb: 1015.0,
//             pressure_in: 29.96,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 72,
//             cloud: 32,
//             feelslike_c: 11.9,
//             feelslike_f: 53.4,
//             windchill_c: 11.9,
//             windchill_f: 53.4,
//             heatindex_c: 13.1,
//             heatindex_f: 55.6,
//             dewpoint_c: 8.1,
//             dewpoint_f: 46.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.1,
//             gust_kph: 22.7,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691391600,
//             time: "2023-08-07 08:00",
//             temp_c: 14.3,
//             temp_f: 57.7,
//             is_day: 1,
//             condition: {
//               text: "Sunny",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
//               code: 1000,
//             },
//             wind_mph: 11.6,
//             wind_kph: 18.7,
//             wind_degree: 283,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.97,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 65,
//             cloud: 41,
//             feelslike_c: 13.7,
//             feelslike_f: 56.7,
//             windchill_c: 13.7,
//             windchill_f: 56.7,
//             heatindex_c: 14.3,
//             heatindex_f: 57.7,
//             dewpoint_c: 7.7,
//             dewpoint_f: 45.9,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.9,
//             gust_kph: 22.3,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691395200,
//             time: "2023-08-07 09:00",
//             temp_c: 15.5,
//             temp_f: 59.9,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 12.1,
//             wind_kph: 19.4,
//             wind_degree: 289,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 58,
//             cloud: 49,
//             feelslike_c: 15.5,
//             feelslike_f: 59.9,
//             windchill_c: 15.5,
//             windchill_f: 59.9,
//             heatindex_c: 15.5,
//             heatindex_f: 59.9,
//             dewpoint_c: 7.4,
//             dewpoint_f: 45.3,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.9,
//             gust_kph: 22.3,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691398800,
//             time: "2023-08-07 10:00",
//             temp_c: 16.6,
//             temp_f: 61.9,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 12.3,
//             wind_kph: 19.8,
//             wind_degree: 289,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 53,
//             cloud: 44,
//             feelslike_c: 16.6,
//             feelslike_f: 61.9,
//             windchill_c: 16.6,
//             windchill_f: 61.9,
//             heatindex_c: 16.6,
//             heatindex_f: 61.9,
//             dewpoint_c: 6.8,
//             dewpoint_f: 44.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.1,
//             gust_kph: 22.7,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691402400,
//             time: "2023-08-07 11:00",
//             temp_c: 17.6,
//             temp_f: 63.7,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 12.3,
//             wind_kph: 19.8,
//             wind_degree: 290,
//             wind_dir: "WNW",
//             pressure_mb: 1015.0,
//             pressure_in: 29.98,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 48,
//             cloud: 39,
//             feelslike_c: 17.6,
//             feelslike_f: 63.7,
//             windchill_c: 17.6,
//             windchill_f: 63.7,
//             heatindex_c: 17.6,
//             heatindex_f: 63.7,
//             dewpoint_c: 6.3,
//             dewpoint_f: 43.3,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.1,
//             gust_kph: 22.7,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691406000,
//             time: "2023-08-07 12:00",
//             temp_c: 18.7,
//             temp_f: 65.7,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 12.5,
//             wind_kph: 20.2,
//             wind_degree: 290,
//             wind_dir: "WNW",
//             pressure_mb: 1016.0,
//             pressure_in: 29.99,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 43,
//             cloud: 34,
//             feelslike_c: 18.7,
//             feelslike_f: 65.7,
//             windchill_c: 18.7,
//             windchill_f: 65.7,
//             heatindex_c: 18.7,
//             heatindex_f: 65.7,
//             dewpoint_c: 5.7,
//             dewpoint_f: 42.3,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.3,
//             gust_kph: 23.0,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691409600,
//             time: "2023-08-07 13:00",
//             temp_c: 18.7,
//             temp_f: 65.7,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 12.5,
//             wind_kph: 20.2,
//             wind_degree: 289,
//             wind_dir: "WNW",
//             pressure_mb: 1016.0,
//             pressure_in: 30.0,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 43,
//             cloud: 56,
//             feelslike_c: 18.7,
//             feelslike_f: 65.7,
//             windchill_c: 18.7,
//             windchill_f: 65.7,
//             heatindex_c: 18.7,
//             heatindex_f: 65.7,
//             dewpoint_c: 5.9,
//             dewpoint_f: 42.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.3,
//             gust_kph: 23.0,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691413200,
//             time: "2023-08-07 14:00",
//             temp_c: 18.7,
//             temp_f: 65.7,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 12.3,
//             wind_kph: 19.8,
//             wind_degree: 288,
//             wind_dir: "WNW",
//             pressure_mb: 1016.0,
//             pressure_in: 30.01,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 44,
//             cloud: 78,
//             feelslike_c: 18.7,
//             feelslike_f: 65.7,
//             windchill_c: 18.7,
//             windchill_f: 65.7,
//             heatindex_c: 18.7,
//             heatindex_f: 65.7,
//             dewpoint_c: 6.2,
//             dewpoint_f: 43.2,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.5,
//             gust_kph: 23.4,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691416800,
//             time: "2023-08-07 15:00",
//             temp_c: 18.7,
//             temp_f: 65.7,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 12.3,
//             wind_kph: 19.8,
//             wind_degree: 287,
//             wind_dir: "WNW",
//             pressure_mb: 1017.0,
//             pressure_in: 30.02,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 44,
//             cloud: 100,
//             feelslike_c: 18.7,
//             feelslike_f: 65.7,
//             windchill_c: 18.7,
//             windchill_f: 65.7,
//             heatindex_c: 18.7,
//             heatindex_f: 65.7,
//             dewpoint_c: 6.4,
//             dewpoint_f: 43.5,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.5,
//             gust_kph: 23.4,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691420400,
//             time: "2023-08-07 16:00",
//             temp_c: 18.4,
//             temp_f: 65.1,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 11.9,
//             wind_kph: 19.1,
//             wind_degree: 285,
//             wind_dir: "WNW",
//             pressure_mb: 1017.0,
//             pressure_in: 30.03,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 49,
//             cloud: 79,
//             feelslike_c: 18.4,
//             feelslike_f: 65.1,
//             windchill_c: 18.4,
//             windchill_f: 65.1,
//             heatindex_c: 18.4,
//             heatindex_f: 65.1,
//             dewpoint_c: 7.3,
//             dewpoint_f: 45.1,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 14.3,
//             gust_kph: 23.0,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691424000,
//             time: "2023-08-07 17:00",
//             temp_c: 18.2,
//             temp_f: 64.8,
//             is_day: 1,
//             condition: {
//               text: "Overcast",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
//               code: 1009,
//             },
//             wind_mph: 11.6,
//             wind_kph: 18.7,
//             wind_degree: 284,
//             wind_dir: "WNW",
//             pressure_mb: 1017.0,
//             pressure_in: 30.03,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 53,
//             cloud: 59,
//             feelslike_c: 18.2,
//             feelslike_f: 64.8,
//             windchill_c: 18.2,
//             windchill_f: 64.8,
//             heatindex_c: 18.2,
//             heatindex_f: 64.8,
//             dewpoint_c: 8.3,
//             dewpoint_f: 46.9,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.9,
//             gust_kph: 22.3,
//             uv: 4.0,
//           },
//           {
//             time_epoch: 1691427600,
//             time: "2023-08-07 18:00",
//             temp_c: 17.9,
//             temp_f: 64.2,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 11.2,
//             wind_kph: 18.0,
//             wind_degree: 283,
//             wind_dir: "WNW",
//             pressure_mb: 1017.0,
//             pressure_in: 30.04,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 57,
//             cloud: 38,
//             feelslike_c: 17.9,
//             feelslike_f: 64.2,
//             windchill_c: 17.9,
//             windchill_f: 64.2,
//             heatindex_c: 17.9,
//             heatindex_f: 64.2,
//             dewpoint_c: 9.2,
//             dewpoint_f: 48.6,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.6,
//             gust_kph: 22.0,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691431200,
//             time: "2023-08-07 19:00",
//             temp_c: 17.0,
//             temp_f: 62.6,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 10.1,
//             wind_kph: 16.2,
//             wind_degree: 280,
//             wind_dir: "W",
//             pressure_mb: 1018.0,
//             pressure_in: 30.06,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 61,
//             cloud: 40,
//             feelslike_c: 17.0,
//             feelslike_f: 62.6,
//             windchill_c: 17.0,
//             windchill_f: 62.6,
//             heatindex_c: 17.0,
//             heatindex_f: 62.6,
//             dewpoint_c: 9.3,
//             dewpoint_f: 48.7,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 13.0,
//             gust_kph: 20.9,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691434800,
//             time: "2023-08-07 20:00",
//             temp_c: 16.0,
//             temp_f: 60.8,
//             is_day: 1,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
//               code: 1003,
//             },
//             wind_mph: 8.9,
//             wind_kph: 14.4,
//             wind_degree: 278,
//             wind_dir: "W",
//             pressure_mb: 1019.0,
//             pressure_in: 30.08,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 65,
//             cloud: 42,
//             feelslike_c: 16.0,
//             feelslike_f: 60.8,
//             windchill_c: 16.0,
//             windchill_f: 60.8,
//             heatindex_c: 16.0,
//             heatindex_f: 60.8,
//             dewpoint_c: 9.5,
//             dewpoint_f: 49.1,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 12.3,
//             gust_kph: 19.8,
//             uv: 5.0,
//           },
//           {
//             time_epoch: 1691438400,
//             time: "2023-08-07 21:00",
//             temp_c: 15.1,
//             temp_f: 59.2,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 7.8,
//             wind_kph: 12.6,
//             wind_degree: 275,
//             wind_dir: "W",
//             pressure_mb: 1019.0,
//             pressure_in: 30.09,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 70,
//             cloud: 44,
//             feelslike_c: 15.1,
//             feelslike_f: 59.2,
//             windchill_c: 15.1,
//             windchill_f: 59.2,
//             heatindex_c: 15.1,
//             heatindex_f: 59.2,
//             dewpoint_c: 9.6,
//             dewpoint_f: 49.3,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.6,
//             gust_kph: 18.7,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691442000,
//             time: "2023-08-07 22:00",
//             temp_c: 14.5,
//             temp_f: 58.1,
//             is_day: 0,
//             condition: {
//               text: "Clear",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
//               code: 1000,
//             },
//             wind_mph: 7.6,
//             wind_kph: 12.2,
//             wind_degree: 276,
//             wind_dir: "W",
//             pressure_mb: 1019.0,
//             pressure_in: 30.1,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 73,
//             cloud: 32,
//             feelslike_c: 14.2,
//             feelslike_f: 57.6,
//             windchill_c: 14.2,
//             windchill_f: 57.6,
//             heatindex_c: 14.5,
//             heatindex_f: 58.1,
//             dewpoint_c: 9.6,
//             dewpoint_f: 49.3,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.4,
//             gust_kph: 18.4,
//             uv: 1.0,
//           },
//           {
//             time_epoch: 1691445600,
//             time: "2023-08-07 23:00",
//             temp_c: 13.9,
//             temp_f: 57.0,
//             is_day: 0,
//             condition: {
//               text: "Partly cloudy",
//               icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
//               code: 1003,
//             },
//             wind_mph: 7.6,
//             wind_kph: 12.2,
//             wind_degree: 277,
//             wind_dir: "W",
//             pressure_mb: 1020.0,
//             pressure_in: 30.11,
//             precip_mm: 0.0,
//             precip_in: 0.0,
//             humidity: 76,
//             cloud: 20,
//             feelslike_c: 13.2,
//             feelslike_f: 55.8,
//             windchill_c: 13.2,
//             windchill_f: 55.8,
//             heatindex_c: 13.9,
//             heatindex_f: 57.0,
//             dewpoint_c: 9.7,
//             dewpoint_f: 49.5,
//             will_it_rain: 0,
//             chance_of_rain: 0,
//             will_it_snow: 0,
//             chance_of_snow: 0,
//             vis_km: 10.0,
//             vis_miles: 6.0,
//             gust_mph: 11.4,
//             gust_kph: 18.4,
//             uv: 1.0,
//           },
//         ],
//       },
//     ],
//   },
// };
